name: traccar_flutter
description: "A Flutter plugin for integrating with the Traccar location tracking platform, providing seamless tracking capabilities for Android and iOS."
version: 1.0.2+4
homepage: "https://github.com/mostafamvh/traccar_flutter"

maintainers:
  - "Mostafa Movahhed <Thisismovahhed@gmail.com>"
  
environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.mostafamovahhed.traccar_flutter
        pluginClass: TraccarFlutterPlugin
      ios:
        pluginClass: TraccarFlutterPlugin
